/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtGender = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        TxtContactNo = new javax.swing.JTextField();
        TxtPasword = new javax.swing.JPasswordField();
        TxtEmail = new javax.swing.JTextField();
        CGender = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        TxtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(255, 255, 255));
        TxtPassword.setText("Password:");
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        TxtGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtGender.setForeground(new java.awt.Color(255, 255, 255));
        TxtGender.setText("Gender:");
        jPanel1.add(TxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        TxtUsername.setBackground(new java.awt.Color(0, 51, 102));
        TxtUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 150, 30));

        TxtContactNo.setBackground(new java.awt.Color(0, 51, 102));
        TxtContactNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtContactNo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 150, 30));

        TxtPasword.setBackground(new java.awt.Color(0, 51, 102));
        TxtPasword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtPasword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 30));

        TxtEmail.setBackground(new java.awt.Color(0, 51, 102));
        TxtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtEmail.setForeground(new java.awt.Color(255, 255, 255));
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 170, 30));

        CGender.setBackground(new java.awt.Color(0, 51, 102));
        CGender.setForeground(new java.awt.Color(255, 255, 255));
        CGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        CGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGenderActionPerformed(evt);
            }
        });
        jPanel1.add(CGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 210, -1));

        btnLogin1.setBackground(new java.awt.Color(0, 51, 102));
        btnLogin1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("Submit");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jLabel7.setText("Login");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGenderActionPerformed

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        if (!"".equals(TxtUsername.getText()) &&!"".equals(TxtContactNo.getText()) &&!"".equals(TxtPassword.getText()) &&!"".equals(TxtEmail.getText()) &&!"".equals(TxtGender.getText())) {
            JOptionPane.showMessageDialog(this,"Succesfully Registered");
            this.dispose();
             Login_Register mainPage = new Login_Register();
             mainPage.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Fill all the missing fields" );
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CGender;
    private javax.swing.JTextField TxtContactNo;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JLabel TxtGender;
    private javax.swing.JLabel TxtPassword;
    private javax.swing.JPasswordField TxtPasword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
